# Generated by Django 4.2.1 on 2023-06-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (3, 'Sci-fi'), (2, 'Komedia'), (4, 'Drama'), (1, 'Horror')], default=0),
        ),
    ]
