# Generated by Django 4.2.2 on 2023-06-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (3, 'Sci-fi'), (0, 'Inne'), (4, 'Drama'), (1, 'Horror')], default=0),
        ),
    ]
