# Generated by Django 4.2.2 on 2023-06-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Drama'), (3, 'Sci-fi'), (0, 'Inne'), (1, 'Horror'), (2, 'Komedia')], default=0),
        ),
    ]
